export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGIN_STATUS = 'AUTH_LOGIN_STATUS';

export const GET_MEALS_SUCCESS = 'GET_MEALS_SUCCESS';
export const GET_MEALS_FAILURE = 'GET_MEALS_FAILURE';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE';
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const UPDATE_MEAL_FAILURE = 'UPDATE_MEAL_FAILURE';
export const REMOVE_MEAL_SUCCESS = 'REMOVE_MEAL_SUCCESS';
export const REMOVE_MEAL_FAILURE = 'REMOVE_MEAL_FAILURE';
export const GET_MEALS_LOADING_STATUS = 'GET_MEALS_LOADING_STATUS';

export const SET_MENU_SUCCESS = 'SET_MENU_SUCCESS';
export const SET_MENU_FAILURE = 'SET_MENU_FAILURE';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const ADD_MEAL_TO_MENU_SUCCESS = 'ADD_MEAL_TO_MENU_SUCCESS';
export const ADD_MEAL_TO_MENU_FAILURE = 'ADD_MEAL_TO_MENU_FAILURE';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';

export const ORDER_MEAL_SUCCESS = 'ORDER_MEAL_SUCCESS';
export const ORDER_MEAL_FAILURE = 'ORDER_MEAL_FAILURE';
export const MODIFY_ORDER_SUCCESS = 'MODIFY_ORDER_SUCCESS';
export const MODIFY_ORDER_FAILURE = 'MODIFY_ORDER_FAILURE';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE';

export const DELIVER_ORDER_SUCCESS = 'DELIVER_ORDER_SUCCESS';
export const DELIVER_ORDER_FAILURE = 'DELIVER_ORDER_FAILURE';


export const GET_ORDERS_BY_DATE_SUCCESS = 'GET_ORDERS_BY_DATE_SUCCESS';
export const GET_ORDERS_BY_DATE_FAILURE = 'GET_ORDERS_BY_DATE_FAILURE';

export const GET_ALL_PREVIOUS_ORDERS_SUCCESS = 'GET_ALL_PREVIOUS_ORDERS_SUCCESS';
export const GET_ALL_PREVIOUS_ORDERS_FAILURE = 'GET_ALL_PREVIOUS_ORDERS_FAILURE';

export const GET_ORDER_LOADING_STATUS = 'GET_ORDER_LOADING_STATUS';

export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
export const GET_PAGINATED_MEALS = 'GET_PAGINATED_MEALS';