
export const GET_MEALS_SUCCESS = 'GET_MEALS_SUCCESS';
export const GET_MEALS_FAILURE = 'GET_MEALS_FAILURE';

export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE';

export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const UPDATE_MEAL_FAILURE = 'UPDATE_MEAL_FAILURE';

export const REMOVE_MEAL_SUCCESS = 'REMOVE_MEAL_SUCCESS';
export const REMOVE_MEAL_FAILURE = 'REMOVE_MEAL_FAILURE';

export const SET_MENU_SUCCESS = 'SET_MENU_SUCCESS';
export const SET_MENU_FAILURE = 'SET_MENU_FAILURE';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';

export const ADD_MEAL_TO_MENU_SUCCESS = 'ADD_MEAL_TO_MENU_SUCCESS';
export const ADD_MEAL_TO_MENU_FAILURE = 'ADD_MEAL_TO_MENU_FAILURE';

export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';
